name: Build, lint & test

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: yarn install
      run: yarn install
    - name: yarn lint
      run: yarn lint
    - name: yarn test
      run: yarn test